all: exercise1 exercise2

exercise1: exercise1.cpp
	g++ exercise1.cpp -lglfw -ldl -lm -lGL -lGLU -lglut -o exercise1

exercise2: exercise2.cpp
	g++ exercise2.cpp -lglfw -ldl -lm -lGL -lGLU -lglut -o exercise2
