CC=g++
CFLAGS= -lglfw -lGL -lGLEW -lglut -lGLU
fullFlags= -Wall -Wpedantic -Wextra -std=gnu17 -lglfw -lGL -lGLEW

default:
	make all

all:
	$(CC) -o Assignment-4 src/main.cpp $(CFLAGS)


run: all
	./Assignment-4
